name: tribes_crowdfunding_interview_project
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cropperx: ^1.1.1
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.10
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.17+1
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  image_picker: ^1.0.2
  intl: 0.18.0
  path_provider: ^2.1.0
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/tokens/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular-400.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold-600.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold-700.ttf
          weight: 700
        - asset: assets/fonts/Inter-Black-900.ttf
          weight: 900
