import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:tribes_crowdfunding_interview_project/theme/colors/coloring.dart';

part 'tribe_color_schema.freezed.dart';

@freezed
class TribeColorsSchema with _$TribeColorsSchema {
  const factory TribeColorsSchema._({
    required Color laserTagReg,
    required Color marsOrange,
    required Color moonCheeseYellow,
    required Color iceColdBlue,
    required Color touchGreenGrass,
    required Color luxuryPurple,
    required Color hawtSalmon,
    required Color nightOwlBlack,
    required Color winterWhite,
    required Color grey70,
    required Color white70p,
    required Color black25p,
    required Color black50p,
    required Color black08p,
    required Color okayColor,
    required Color errorColor,
    required Color indicatorColor,
    required Color red50p,
    required Color webCardBackgroundColor,
    required Color twitterCardBackgroundColor,
    required Color separatorColor,
    required Color baseNavigationBarColor,
    required Color textEntitySymbolColor,
    required Color baseNav,
    required Color baseContent,
    required Color label1text,
    required Color label2text,
    required Color label1,
    required Color label2,
    required Color label3,
    required Color label4,
    required Color labet5,
    required Color label6,
    required Color header1,
    required Color header2,
    required Color header3,
    required Color header4,
    required Color header45,
    required Color header5,
    required Color body,
    required Color secondary,
    required Color caption,
    required Color unread,
    required Color coinbaseBackground,
  }) = _TribeColorsSchema;

  factory TribeColorsSchema.light() => TribeColorsSchema._(
        laserTagReg: Coloring.laserTagReg,
        marsOrange: Coloring.marsOrange,
        moonCheeseYellow: Coloring.moonCheeseYellow,
        iceColdBlue: Coloring.iceColdBlue,
        touchGreenGrass: Coloring.touchGreenGrass,
        luxuryPurple: Coloring.luxuryPurple,
        hawtSalmon: Coloring.hawtSalmon,
        nightOwlBlack: Coloring.nightOwlBlack,
        winterWhite: Coloring.winterWhite,
        grey70: Coloring.grey70,
        white70p: Coloring.white70p,
        black25p: Coloring.black25p,
        black50p: Coloring.black50p,
        black08p: Coloring.black08p,
        okayColor: Coloring.okayColor,
        errorColor: Coloring.errorColor,
        indicatorColor: Coloring.indicatorColor,
        red50p: Coloring.red50p,
        webCardBackgroundColor: Coloring.webCardBackgroundColor,
        twitterCardBackgroundColor: Coloring.twitterCardBackgroundColor,
        separatorColor: Coloring.separatorColor,
        baseNavigationBarColor: Coloring.baseNavigationBarColor,
        textEntitySymbolColor: Coloring.textEntitySymbolColor,
        baseNav: Coloring.baseNavLight,
        baseContent: Coloring.baseContentLight,
        label1text: Colors.red,
        label2text: Coloring.labelLight2text,
        label1: Coloring.labelLight1,
        label2: Coloring.labelLight2,
        label3: Coloring.labelLight3,
        label4: Coloring.labelLight4,
        labet5: Coloring.labelLight5,
        label6: Coloring.labelLight6,
        header1: Coloring.header1,
        header2: Coloring.header2,
        header3: Coloring.header3,
        header4: Coloring.header4,
        header45: Coloring.header45,
        header5: Coloring.header5,
        body: Coloring.body,
        secondary: Coloring.secondary,
        caption: Coloring.caption,
        unread: Coloring.unread,
        coinbaseBackground: Coloring.coinbaseBackground,
      );

  factory TribeColorsSchema.dark() => TribeColorsSchema._(
        laserTagReg: Coloring.laserTagReg,
        marsOrange: Coloring.marsOrange,
        moonCheeseYellow: Coloring.moonCheeseYellow,
        iceColdBlue: Coloring.iceColdBlue,
        touchGreenGrass: Coloring.touchGreenGrass,
        luxuryPurple: Coloring.luxuryPurple,
        hawtSalmon: Coloring.hawtSalmon,
        nightOwlBlack: Coloring.nightOwlBlack,
        winterWhite: Coloring.winterWhite,
        grey70: Coloring.grey70,
        white70p: Coloring.white70p,
        black25p: Coloring.black25p,
        black50p: Coloring.black50p,
        black08p: Coloring.black08p,
        okayColor: Coloring.okayColor,
        errorColor: Coloring.errorColor,
        indicatorColor: Coloring.indicatorColor,
        red50p: Coloring.red50p,
        webCardBackgroundColor: Coloring.webCardBackgroundColor,
        twitterCardBackgroundColor: Coloring.twitterCardBackgroundColor,
        separatorColor: Coloring.separatorColor,
        baseNavigationBarColor: Coloring.baseNavigationBarColor,
        textEntitySymbolColor: Coloring.textEntitySymbolColor,
        baseNav: Coloring.baseNavDark,
        baseContent: Coloring.baseContentDark,
        label1text: Colors.blue,
        label2text: Coloring.labelDark2text,
        label1: Coloring.labelDark1,
        label2: Coloring.labelDark2,
        label3: Coloring.labelDark3,
        label4: Coloring.labelDark4,
        labet5: Coloring.labelDark5,
        label6: Coloring.labelDark6,
        header1: Coloring.header1,
        header2: Coloring.header2,
        header3: Coloring.header3,
        header4: Coloring.header4,
        header45: Coloring.header45,
        header5: Coloring.header5,
        body: Coloring.body,
        secondary: Coloring.secondary,
        caption: Coloring.caption,
        unread: Coloring.unread,
        coinbaseBackground: Coloring.coinbaseBackground,
      );
}
